### ISSUE TITLE
I don't see the option to add multiple partners for 2c2

### ISSUE THREAD

**Issue by Angernoxo** [neveralone-gg/beta-test#1]
I have created a group but I do not see the option to add multiple compositions.

E.g. I play Protection Paladin, and I would like to search for Fire Mages, Warriors etc, but the listing group tool doesn't give me the option to do so.

Atleast, in Firefox .

Would be nice to have the option to add for multiple partner / comps on the same group.

Also , the search groups option is permanently loading, and not displaying any group.
If there are no groups, it should display as " there are no groups avaliable right now " or something like that, but having the bar permanently saying "looking for groups" while not showing any makes it look like there is a problem loading them.

**Comment by neveralone-gg** [comment]
Hey @Angernoxo 

Thanks for reporting this issue, much appreciated!

Currently there is indeed a bug which prevents you from specifying multiple compositions on the same group. In the free tier it should be possible to specify 2 compositions per group and with Premium subscription you will get 1 extra plus the wildcard option. I will fix this as soon as possible and hope this is acceptable.

The loading indication is not optimal indeed. It should just indicate that a manual refresh is not needed and if a group matches the search criteria it will appear automatically.

**Comment by jarwong** [comment]
Is there a reason you're not intending to allow unlimited compositions (up to # of classes...) for the premium tier?  Some comps can be very flexible with the third class.

**Comment by neveralone-gg** [comment]
@jarwong 
The limits might change in the future. Trying to figure out what makes sense in the beta. But unlimited is very unlikely.

**Comment by neveralone-gg** [comment]
Fixed with v0.2.0
